name: ✨ Feature Request
description: Suggest a new feature or enhancement for Coding Party 2026
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        
        We love hearing ideas from our community. Please provide as much detail as possible to help us understand your suggestion.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and discussions to ensure this feature hasn't been requested before
          required: true
        - label: I have read the [project vision](../../docs/vision.md) and [roadmap](../../docs/roadmap.md)
          required: true
        - label: This feature aligns with the project's open-source and community-first principles
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Application/Product
        - Frontend Enhancement
        - Backend Enhancement
        - AI/ML Feature
        - Developer Experience
        - Documentation
        - Community Tool
        - Infrastructure
        - Design System
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Who would benefit from it?
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Currently, users face the problem of...
        This affects [who] because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: |
        I would like to see...
        This could work by...
        The user experience would be...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Alternative approach 1: ...
        Alternative approach 2: ...
        
        I prefer the main solution because...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you and the community?
      options:
        - Low - Nice to have, not urgent
        - Medium - Would improve user experience significantly
        - High - Important for project success
        - Critical - Blocking major use cases
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change, minimal impact
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Major - Large feature requiring multiple contributors
        - Unknown - Not sure about complexity
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Provide specific user stories or use cases
      placeholder: |
        1. As a new contributor, I want to... so that...
        2. As a project maintainer, I want to... so that...
        3. As an end user, I want to... so that...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Users can...
        - [ ] The system should...
        - [ ] Documentation includes...
        - [ ] Tests cover...

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups or Examples
      description: Include any mockups, wireframes, or examples that illustrate your idea
      placeholder: |
        Attach images, link to similar features in other projects, or describe the visual/interaction design

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects, constraints, or requirements to consider?
      placeholder: |
        - Performance requirements
        - Security considerations
        - Compatibility requirements
        - Integration points
        - Dependencies

  - type: checkboxes
    id: impact-areas
    attributes:
      label: Impact Areas
      description: Which areas of the project would this feature affect?
      options:
        - label: User Interface/Experience
        - label: API Design
        - label: Database Schema
        - label: Security
        - label: Performance
        - label: Documentation
        - label: Testing
        - label: CI/CD Pipeline
        - label: Community Processes

  - type: textarea
    id: community-benefit
    attributes:
      label: Community Benefit
      description: How would this feature benefit the broader community?
      placeholder: |
        This feature would help the community by...
        It aligns with our values of...
        Expected impact on contributor onboarding/retention...
    validations:
      required: true

  - type: checkboxes
    id: contribution-interest
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with design/planning
        - label: I can help with testing
        - label: I can help with documentation
        - label: I would like to collaborate with others on this
        - label: I'm suggesting this but cannot contribute to implementation

  - type: textarea
    id: timeline
    attributes:
      label: Suggested Timeline
      description: When would you like to see this feature implemented?
      placeholder: |
        - Ideal timeline: ...
        - Any specific deadlines or events this relates to: ...
        - Flexibility: ...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        - Related issues or discussions
        - Similar features in other projects
        - Research or data supporting this request
        - Community feedback you've received

  - type: markdown
    attributes:
      value: |
        ---
        
        Thank you for your feature suggestion! 🚀
        
        Our community will review this request and discuss it in the comments. We encourage you to:
        
        - Join the discussion in [GitHub Discussions](../../discussions)
        - Share this with other community members for feedback
        - Consider starting a proof-of-concept if you're interested in contributing
        
        Feature requests that align with our vision and have community support are more likely to be implemented!